id: 21e1f0532b46488c9b3f340ca5114582
initial_creation_type: ocr
source_metadata:
  volumes:
    90ce22f138a04a86b5eccdfb08dfe877:
      base_file: v022.txt
      image_group_id: I1PD95867
      title: དཔལ་གསང་བ་འདུས་པའི་བསྟོད་པ།
      total_pages: 1409
      volume_number: 22
